name: Close stale issues

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          # Issues
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          close-issue-message: 'This issue was closed because it has been stale for 30 days with no activity.'
          days-before-issue-stale: 60
          days-before-issue-close: 30

          # Pull Requests
          stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          close-pr-message: 'This pull request was closed because it has been stale for 30 days with no activity.'
          days-before-pr-stale: 60
          days-before-pr-close: 30

          # General settings
          exempt-issue-labels: 'pinned,security'
          exempt-pr-labels: 'pinned,security'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'